-- init_clean.sql - cleaned version of init.sql (removed redundant ALTER)

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `kind` ENUM('student','teacher') DEFAULT 'student',
  `role` ENUM('admin','user') DEFAULT 'user',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `attendance` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `type` ENUM('in','out') NOT NULL,
  `note` VARCHAR(255) DEFAULT NULL,
  `recorded_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed users: admin, a teacher, and a student (passwords shown for seed purposes only)
INSERT INTO users (email,password,name,role,kind)
SELECT 'admin@example.com', '$2y$10$rIpwg/3Amurd6xBuiqxhVO.sT4Ev6emHQB/cD/eTgkUaq0agTpOnu', 'Administrator', 'admin', 'teacher'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='admin@example.com');

INSERT INTO users (email,password,name,role,kind)
SELECT 'teacher1@example.com', '$2y$10$kna2B7kkfpUJoNAlGglLuuS1ArRt/sAUYDM2RciGddlp4P2DkRiT.', 'Teacher One', 'user', 'teacher'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='teacher1@example.com');

INSERT INTO users (email,password,name,role,kind)
SELECT 'student1@example.com', '$2y$10$GUuJVSZolK0Tja//JnmhluM5O4M1lEfN5wfAldbivYm.St7rnkVPq', 'Student One', 'user', 'student'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='student1@example.com');

-- Note: password hashes above were generated by the PHP runtime and correspond to Admin@123 / Teacher@123 / Student@123
